name: Trigger PR in test2 on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  trigger_pr_in_test2:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: echo "$PAT_TOKEN" | gh auth login --with-token

      - name: Create PR in test2 repo
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          TARGET_REPO="Gokulakrishnan-k/test2"
          BRANCH_NAME="auto-pr-from-test1-${{ github.event.pull_request.number }}"

          git clone https://github.com/$TARGET_REPO.git
          cd test2
          git checkout -b $BRANCH_NAME

          # Create empty commit to trigger PR
          git commit --allow-empty -m "Trigger PR from test1 PR #${{ github.event.pull_request.number }}"

          git push origin $BRANCH_NAME

          gh pr create --repo $TARGET_REPO --head $BRANCH_NAME --title "Auto PR triggered by merged PR #${{ github.event.pull_request.number }} in test1" --body "This PR was automatically created after merging PR #${{ github.event.pull_request.number }} in test1."
