name: Trigger PR in test2 on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  trigger_pr_in_test2:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo (optional, if needed)
        uses: actions/checkout@v3

      - name: Create PR in test2 repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Your PAT with repo access
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Install GitHub CLI if not installed
          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh
          fi

          TARGET_REPO="Gokulakrishnan-k/test2"
          BRANCH_NAME="auto-pr-from-test1-${{ github.event.pull_request.number }}"

          # Clone target repo with authentication
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/$TARGET_REPO.git
          cd test2

          # Create a new branch and empty commit
          git checkout -b $BRANCH_NAME
          git commit --allow-empty -m "Trigger PR from test1 PR #${{ github.event.pull_request.number }}"

          # Push branch to remote
          git push origin $BRANCH_NAME

          # Create the PR using gh CLI (automatically uses GITHUB_TOKEN)
          gh pr create --repo $TARGET_REPO \
            --head $BRANCH_NAME \
            --title "Auto PR triggered by merged PR #${{ github.event.pull_request.number }} in test1" \
            --body "This PR was automatically created after merging PR #${{ github.event.pull_request.number }} in test1."
