name: Trigger PR in test2 on PR merge with [AVO] check

on:
  pull_request:
    types: [closed]

jobs:
  trigger_pr_in_test2:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (optional, if needed)
        uses: actions/checkout@v3

      - name: Check for [AVO] in merge commit message
        id: check_avo
        run: |
          # Fetch the merge commit message using git
          COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}
          echo "Merge commit SHA: $COMMIT_SHA"
          
          # Fetch the commit message
          COMMIT_MSG=$(git log -1 --pretty=%B $COMMIT_SHA)
          echo "Commit message: $COMMIT_MSG"

          # Check if message contains [AVO]
          if echo "$COMMIT_MSG" | grep -q "\[AVO\]"; then
            echo "AVO found in commit message"
            echo "has_avo=true" >> $GITHUB_OUTPUT
          else
            echo "AVO not found in commit message"
            echo "has_avo=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR in test2 repo
        if: steps.check_avo.outputs.has_avo == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh
          fi

          TARGET_REPO="Gokulakrishnan-k/test2"
          BRANCH_NAME="auto-pr-from-test1-${{ github.event.pull_request.number }}"

          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/$TARGET_REPO.git
          cd test2

          git checkout -b $BRANCH_NAME
          git commit --allow-empty -m "Trigger PR from test1 PR #${{ github.event.pull_request.number }}"

          git push origin $BRANCH_NAME

          gh pr create --repo $TARGET_REPO \
            --head $BRANCH_NAME \
            --title "Auto PR triggered by merged PR #${{ github.event.pull_request.number }} in test1" \
            --body "This PR was automatically created after merging PR #${{ github.event.pull_request.number }} in test1 with [AVO] in commit message."
